theme: jekyll-theme-cayman
title: Spamr
description: Spamr is an all-platform spambot.
show_downloads: true
github:
  zip_url: https://github.com/jaiveertalwar/spamr/releases/download/v1.0.3/Spamr-1.0.3.pkg
  another_url: https://github.com/jaiveertalwar/spamr/archive/refs/tags/v1.0.3.zip
  

